# Welcome to Jekyll!
#
title: Jorge Moratilla
email: jorge@moratilla.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Jorge Moratilla, curious and passionate IT guy.
    This is my web site, it may contain nuts and bolts.
    The ideas exposed here are my own.
twitter_username: jmoratilla
github_username:  jmoratilla
logo: /assets/img/jmoratilla.jpg
url: "https://www.moratilla.com"

# Authors
author:
  name: Jorge Moratilla
  email: jorge@moratilla.com

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-twitter-plugin
  - jekyll-youtube

# Google Analytics
google_analytics: UA-124601299-1

# Hydejack customization
accent_image: /assets/img/background.jpg
font_heading: "'Roboto Slab', Helvetica, Arial, sans-serif"
google_fonts: "Roboto+Slab:700|Noto+Sans:400,400i,700,700i"

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2020. All rights reserved.

# Format of the permalinks
permalink: /:categories/:year/:month/:title/

# Pagination
paginate: 10
paginate_path: /page-:num/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  repositories:
    output: true
    permalink: /repositories/:path/
  talks:
    output: true
    permalink: /talks/:path/
  books:
    output: true
    permalink: /books/:path/

# Sidebar
defaults:
  - scope:
      path: about.md
    values:
      menu: true
      order: 1
  - scope:
      path: repositories.md
    values:
      menu: true
      order: 2
  - scope:
      path: talks.md
    values:
      menu: true
      order: 3
  - scope:
      path: books.md
    values:
      menu: true
      order: 4
  - scope:
      path: projects.md
    values:
      menu: true
      order: 5

# Exclude from processing.
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

# Building the Site
compress_html:
  comments:  ["<!-- ", " -->"]
  clippings: all
  endings:   all

sass:
  style:     compressed

hydejack:
  use_lsi: true